Update documentation to new structure
ballerina-platform/module-ballerinax-googleapis.sheets pull request #178
Opened 2021-07-14 19:51 UTC by RolandHewage

## Purpose
> 
The connector team have agreed on a common format for documentations
https://docs.google.com/document/d/1WZg1ix9MpKDTQ_OOm3NVqhQ5L0VGNaUQ1LRmjp-SMO4/edit?usp=sharing
This format should be included in the relevant connectors

Resolves https://github.com/wso2-enterprise/choreo/issues/6683

## Goals
> Update documentation to new structure

## Approach
> Update documentation to new structure
https://docs.google.com/document/d/1WZg1ix9MpKDTQ_OOm3NVqhQ5L0VGNaUQ1LRmjp-SMO4/edit?usp=sharing

## Release note
>
Update documentation to new structure
https://docs.google.com/document/d/1WZg1ix9MpKDTQ_OOm3NVqhQ5L0VGNaUQ1LRmjp-SMO4/edit?usp=sharing

## Documentation
> https://docs.google.com/document/d/1WZg1ix9MpKDTQ_OOm3NVqhQ5L0VGNaUQ1LRmjp-SMO4/edit?usp=sharing

## Automation tests
 - Unit tests 
   > Done
 - Integration tests
   > Done

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

## Test environment
> 
JDK 11
Ballerina Beta 2
Ubuntu 20.04

2021-08-02 19:01 UTC, RolandHewage commented on README.md
>  [Google Sheets](https://developers.google.com/sheets/api) is an online spreadsheet that lets users create and format spreadsheets and simultaneously work with other people. It lets us manage spreadsh
Fixed in d34f6b7. Thank you.

2021-08-02 19:01 UTC, RolandHewage commented on README.md
> +The Google Spreadsheet [Ballerina](https://ballerina.io/) Connector allows you to access the [Google Spreadsheet API Version v4](https://developers.google.com/sheets/api) through Ballerina. The conne
Yes. It's better. Fixed in d34f6b7. Thank you.

2021-08-02 19:02 UTC, RolandHewage commented on README.md
> +The Google Spreadsheet [Ballerina](https://ballerina.io/) listener allows you to listen to Google Sheets events. It can listen to events triggered  when a spreadsheet is edited such as when a row is
Fixed in d34f6b7. Thank you.

2021-08-03 08:11 UTC, RolandHewage commented on README.md
> +For more information, go to the module(s).
This is the common format decided to use across all the connectors by the team since we maintain separate branches for each Ballerina version. So it's not possible to modify this suggested change unless the team agree. Thank you for the suggestion.

Refer https://github.com/ballerina-platform/module-ballerinax-twilio/pull/110/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R12

2021-08-04 03:35 UTC, RolandHewage commented on README.md
> +### Setting Up the prerequisites
It's not there in the common structure decided by the team
https://docs.google.com/document/d/1WZg1ix9MpKDTQ_OOm3NVqhQ5L0VGNaUQ1LRmjp-SMO4/edit?usp=sharing
So it's not possible to modify this suggested change unless the team agree. Thank you for the suggestion.

2021-08-04 03:41 UTC, RolandHewage commented on README.md
>  For more information, go to the [contribution guidelines](https://github.com/ballerina-platform/ballerina-lang/blob/master/gsheet/CONTRIBUTING.md).
It's not there in the common structure decided by the team
https://docs.google.com/document/d/1WZg1ix9MpKDTQ_OOm3NVqhQ5L0VGNaUQ1LRmjp-SMO4/edit?usp=sharing
So it's not possible to modify this suggested change unless the team agree. You can comment in the common structure doc. Thank you for the suggestion.

2021-08-04 03:43 UTC, RolandHewage commented on README.md
>  * Discuss the code changes of the Ballerina project in [ballerina-dev@googlegroups.com](mailto:ballerina-dev@googlegroups.com).
It's not there in the common structure decided by the team
https://docs.google.com/document/d/1WZg1ix9MpKDTQ_OOm3NVqhQ5L0VGNaUQ1LRmjp-SMO4/edit?usp=sharing
So it's not possible to modify this suggested change unless the team agree. You can comment in the common structure doc. Thank you for the suggestion.

2021-08-04 03:44 UTC, RolandHewage commented on README.md
> +Execute the commands below to build from the source after installing Ballerina.
Resolved & force pushed. Thank you.

2021-08-04 04:02 UTC, RolandHewage commented on README.md
>  1. To clone the repository:
Resolved & forced pushed the changes. Thank you.

2021-08-04 04:25 UTC, shaniR requested changes

2021-08-04 04:25 UTC, shaniR commented on gsheet/Module.md
> +* Create Spreadsheet with given name
End the bullet points with a period.

2021-08-04 04:25 UTC, shaniR commented on gsheet/Package.md
> +The `ballerinax/googleapis.sheets` is a [Ballerina](https://ballerina.io/) connector for Google Sheets.
Shall we merge these sentences into one paragraph?

2021-08-04 04:25 UTC, shaniR commented on gsheet/modules/listener/Module.md
> +Ballerina listener for Google Sheets provides the capability to listen to simple events using the triggers via [App Scripts](https://developers.google.com/apps-script/guides/triggers). App Scripts ru
using the triggers in/ provided in the App scripts?

2021-08-04 04:25 UTC, shaniR commented on gsheet/modules/listener/Module.md
> +Ballerina listener for Google Sheets provides the capability to listen to simple events using the triggers via [App Scripts](https://developers.google.com/apps-script/guides/triggers). App Scripts ru
Can you elaborate more on "The Google sheet listener can listen to these events triggered for a different type of changes and execute the user logic when an event with one of the above change event type is received." ?
I am not sure I understand you fully.

2021-08-04 04:25 UTC, shaniR commented on gsheet/modules/listener/Module.md
> +Ballerina listener for Google Sheets provides the capability to listen to simple events using the triggers via [App Scripts](https://developers.google.com/apps-script/guides/triggers). App Scripts ru
Do we need these information here ? " By using the `/onEdit` service endpoint that listens to edit events with the trigger methods `onAppendRow`, `onUpdateRow`, the google sheets listener gets triggered when a spreadsheet is edited and can get more information about the edit event such as the `spreadsheet ID, spreadsheet name, worksheet ID, worksheet name, range updated, starting row position, end row position, starting column position, end column position, new values, last row with content, last column with content, data related to the Google App Script edit event object`etc." 
it is very specific and technical. I suppose we should give an overview  and  keep it simple for users to learn, what this connector is, what you can do with this, and if there are any advantages of using it.

2021-08-04 04:25 UTC, shaniR commented on gsheet/modules/listener/Module.md
> +Ballerina listener for Google Sheets provides the capability to listen to simple events using the triggers via [App Scripts](https://developers.google.com/apps-script/guides/triggers). App Scripts ru
Let's rephrase, the first half of the para as follows " Ballerina listener for Google Sheets provides the capability to listen to simple events using the [App Scripts](https://developers.google.com/apps-script/guides/triggers) triggers. App Scripts runs a function automatically whenever a certain event occurs, for example, when a user changes a value in a spreadsheet. When an event is triggered, Apps Script passes the event object ( typically `e`) as an argument to the function. The event object contains information about the context that caused the event to trigger. Using App Script [Installable triggers](https://developers.google.com/apps-script/guides/triggers/installable) we can invoke services that require authorization and pass the event information."

2021-08-04 04:25 UTC, shaniR commented on gsheet/modules/listener/Module.md
> +This module supports [Google App Scripts](https://developers.google.com/apps-script/guides/triggers).
is there any particular version?

2021-08-04 04:25 UTC, shaniR commented on gsheet/modules/listener/Module.md
>  We need to enable the app script trigger if we want to listen to internal changes of a spreadsheet. Follow the following steps to enable the trigger.
Shall we rephrase it as  "Follow the steps below to enable the App Script trigger to listen to internal changes of a spreadsheet."

2021-08-04 04:25 UTC, shaniR commented on gsheet/modules/listener/Module.md
>  1. Open the Google sheet that you want to listen to internal changes.
Open the google sheet.

2021-08-04 04:25 UTC, shaniR commented on gsheet/modules/listener/Module.md
>  8. Then make sure you 'Choose which function to run' is `atChange` then 'Select event source' is `From spreadsheet` then 'Select event type' is  `On change` then click Save!.
Shall we list them down? 
8. Select the following values for the following fields. 
   | Field                                          | Value                                      |
   |------------------------------------------|----------------------------------------|
   | Choose which function to run   | `atChange `                              |
   | Select event source                  | `From spreadsheet`                 |
   | Select event type                      | `On change`                             |

2021-08-04 04:25 UTC, shaniR commented on gsheet/modules/listener/Module.md
>  9. This will prompt you to authorize your script to connect to an external service. Click “Review Permissions” and then “Allow” to continue.
If we are using `` for values, let's use it at all places. Let's avoid using ""

2021-08-04 04:25 UTC, shaniR commented on gsheet/modules/listener/Module.md
>  10. Repeat the same process, add a new trigger this time choose this 'Choose which function to run' is `atEdit` then 'Select event source' is `From spreadsheet` then 'Select event type' is  `On edit`
Let's format this as above.

2021-08-04 04:25 UTC, shaniR commented on gsheet/modules/listener/Module.md
> +11. Your triggers will now work as you expect, if you go edit any cell and as soon as you leave that cell this trigger will run and it will hit your endpoint with the data.
You have now configured your triggers. You can test these triggers by editing the google sheet.

2021-08-04 04:25 UTC, shaniR commented on gsheet/modules/listener/Module.md
> +> **NOTE:**
Do we need this? If we do, 
1) We can mention it as a step
2) Use proper note syntax !!! note

2021-08-04 04:25 UTC, shaniR commented on gsheet/modules/listener/Module.md
> +    > **NOTE:**
Do we need to mention this as a note. Isn't this a description?

2021-08-04 04:25 UTC, shaniR commented on gsheet/samples/README.md
>  Sample is available at:
Are we having this file? I believe we decided to remove this file? If not, we need to have it for all connectors.

2021-08-04 18:28 UTC, RolandHewage commented on README.md
> +[Google Sheets](https://developers.google.com/sheets/api) is an online spreadsheet that allows you to create and format spreadsheets. It facilitates multiple users to work on the same spreadsheets si
Resolved and amended the changes. Thank you for the suggestion.

2021-08-04 18:29 UTC, RolandHewage commented on README.md
> +The Google Spreadsheet [Ballerina](https://ballerina.io/) connector allows you to access the [Google Spreadsheet API Version v4](https://developers.google.com/sheets/api) via Ballerina. you can imple
I removed the repeated line in the previous paragraph. Resolved and amended the changes. Thank you for the suggestion.

2021-08-04 18:29 UTC, RolandHewage commented on README.md
> +The Google Spreadsheet [Ballerina](https://ballerina.io/) listener allows you to listen to Google Sheets events. It can listen to events that are triggered when a spreadsheet is edited e.g., when a r
Resolved and amended the changes. Thank you for the suggestion.

2021-08-04 18:31 UTC, RolandHewage commented on README.md
> +- [ballerinax/googleapis.sheets](gsheet/Module.md)
This was not there in the common format. So it would be better if you can comment that suggestion here.
https://docs.google.com/document/d/1WZg1ix9MpKDTQ_OOm3NVqhQ5L0VGNaUQ1LRmjp-SMO4/edit?usp=sharing

2021-08-04 18:31 UTC, RolandHewage commented on gsheet/Module.md
> +Ballerina connector for Google Sheets provides access to the Google Sheets via Ballerina language to implement some of the most common use cases of Google Sheets. The connector provides the capabilit
Resolved and amended the changes. Thank you for the suggestion.

2021-08-04 18:31 UTC, RolandHewage commented on gsheet/Module.md
> +This module supports [Google Sheets API](https://developers.google.com/sheets/api) v4 version.
Resolved and amended the changes. Thank you for the suggestion.

2021-08-04 18:32 UTC, RolandHewage commented on gsheet/Module.md
> +- Create [Google account](https://accounts.google.com/signup/v2/webcreateaccount?utm_source=ga-ob-search&utm_medium=google-account&flowName=GlifWebSignIn&flowEntry=SignUp)
This was not there in the common format. So it would be better if you can comment that suggestion here.
https://docs.google.com/document/d/1WZg1ix9MpKDTQ_OOm3NVqhQ5L0VGNaUQ1LRmjp-SMO4/edit?usp=sharing

2021-08-04 18:33 UTC, RolandHewage commented on gsheet/Module.md
> +First, import the `ballerinax/googleapis.sheets` module into the Ballerina project.
Resolved and amended the changes. Thank you for the suggestion.

2021-08-04 18:34 UTC, RolandHewage commented on gsheet/Module.md
> +    Create Spreadsheet with given name
This was agreed to use in this way in the common format. So it would be better if you can comment that suggestion here.
https://docs.google.com/document/d/1WZg1ix9MpKDTQ_OOm3NVqhQ5L0VGNaUQ1LRmjp-SMO4/edit?usp=sharing

2021-08-04 18:37 UTC, RolandHewage commented on gsheet/Module.md
> +**Note:** Spreadsheet ID is available in the spreadsheet URL "https://docs.google.com/spreadsheets/d/" + <SPREADSHEET_ID> + "/edit#gid=" + <WORKSHEET_ID>.
I modified using 
> **!!! Note:**
Not sure if it's the correct way.

2021-08-04 18:37 UTC, RolandHewage commented on gsheet/Module.md
> +* Create Spreadsheet with given name
Resolved and amended the changes. Thank you for the suggestion.

2021-08-04 18:37 UTC, RolandHewage commented on gsheet/Package.md
> +The `ballerinax/googleapis.sheets` is a [Ballerina](https://ballerina.io/) connector for Google Sheets.
Resolved and amended the changes. Thank you for the suggestion.

2021-08-04 18:38 UTC, RolandHewage commented on gsheet/modules/listener/Module.md
> +Ballerina listener for Google Sheets provides the capability to listen to simple events using the triggers via [App Scripts](https://developers.google.com/apps-script/guides/triggers). App Scripts ru
Resolved and amended the changes. Thank you for the suggestion.

2021-08-04 18:38 UTC, RolandHewage commented on gsheet/modules/listener/Module.md
>  1. Open the Google sheet that you want to listen to internal changes.
Resolved and amended the changes. Thank you for the suggestion.

2021-08-04 18:38 UTC, RolandHewage commented on gsheet/modules/listener/Module.md
>  8. Then make sure you 'Choose which function to run' is `atChange` then 'Select event source' is `From spreadsheet` then 'Select event type' is  `On change` then click Save!.
Resolved and amended the changes. Thank you for the suggestion.

2021-08-04 18:38 UTC, RolandHewage commented on gsheet/modules/listener/Module.md
>  9. This will prompt you to authorize your script to connect to an external service. Click “Review Permissions” and then “Allow” to continue.
Resolved and amended the changes. Thank you for the suggestion.

2021-08-04 18:38 UTC, RolandHewage commented on gsheet/modules/listener/Module.md
>  10. Repeat the same process, add a new trigger this time choose this 'Choose which function to run' is `atEdit` then 'Select event source' is `From spreadsheet` then 'Select event type' is  `On edit`
Resolved and amended the changes. Thank you for the suggestion.

2021-08-04 18:39 UTC, RolandHewage commented on gsheet/modules/listener/Module.md
> +11. Your triggers will now work as you expect, if you go edit any cell and as soon as you leave that cell this trigger will run and it will hit your endpoint with the data.
Resolved and amended the changes. Thank you for the suggestion.

2021-08-04 18:39 UTC, RolandHewage commented on gsheet/modules/listener/Module.md
> +> **NOTE:**
Resolved and amended the changes. Thank you for the suggestion.

2021-08-04 18:41 UTC, RolandHewage commented on gsheet/modules/listener/Module.md
> +    > **NOTE:**
Since no any additional information is added in the common format.
https://docs.google.com/document/d/1WZg1ix9MpKDTQ_OOm3NVqhQ5L0VGNaUQ1LRmjp-SMO4/edit?usp=sharing
This information is added as a note.

2021-08-04 18:42 UTC, RolandHewage commented on gsheet/samples/README.md
>  Sample is available at:
This file is removed now. Sorry it was mistakenly added before. Thank you.

2021-08-04 18:42 UTC, RolandHewage commented on gsheet/modules/listener/Module.md
> +This module supports [Google App Scripts](https://developers.google.com/apps-script/guides/triggers).
There is no particular version

2021-08-04 18:42 UTC, RolandHewage commented on gsheet/modules/listener/Module.md
>  We need to enable the app script trigger if we want to listen to internal changes of a spreadsheet. Follow the following steps to enable the trigger.
Resolved and amended the changes. Thank you for the suggestion.

2021-08-05 08:42 UTC, abeykoon approved these changes

2021-08-05 08:42 UTC, merged

2021-08-16 01:55 UTC, shaniR commented on gsheet/client.bal
> +# The connector let you perform spreadsheet management operations, worksheet management operations and
lets

2021-08-16 01:55 UTC, shaniR commented on gsheet/client.bal
> +# The connector let you perform spreadsheet management operations, worksheet management operations and
worksheet management operations,

2021-08-16 01:55 UTC, shaniR commented on gsheet/client.bal
> +    # Initializes the connector. During initialization you can pass either http:BearerTokenConfig
either the

2021-08-16 01:55 UTC, shaniR commented on gsheet/client.bal
> +    # Initializes the connector. During initialization you can pass either http:BearerTokenConfig
or the

2021-08-16 01:55 UTC, shaniR commented on gsheet/client.bal
> +    # Initializes the connector. During initialization you can pass either http:BearerTokenConfig
OAuth 2.0

2021-08-16 01:55 UTC, shaniR commented on gsheet/client.bal
> +    # Configure the OAuth2 tokens to have the [required permissions](https://developers.google.com/sheets/api/guides/authorizing).
OAuth 2.0